build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.20"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20"
  i386: "ghcr.io/home-assistant/i386-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "SmartLivingNEXT Dataspace Synchronization"
  org.opencontainers.image.description: "Install SmartLivingNEXT Dataspace Synchronization"
  org.opencontainers.image.source: "https://github.com/connected-intelligent-systems/ha_thingsboard"
  org.opencontainers.image.licenses: "MIT License"